//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyTransfer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class address_details
    {
        public int ID { get; set; }
        public string trans_id { get; set; }
        public string Full_Name { get; set; }
        public string phone_num { get; set; }
        public string email { get; set; }
        public string city { get; set; }
        public string address_type { get; set; }
        public string username { get; set; }
    }
}
