//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyTransfer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_NotificationTbl
    {
        public int ID { get; set; }
        public string username { get; set; }
        public string Name { get; set; }
        public string email { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public Nullable<bool> IsRead { get; set; }
    }
}
