//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyTransfer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BalanceTbl
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> ActiveDollars { get; set; }
        public string Acc_Num { get; set; }
    }
}
