//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyTransfer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Transaction
    {
        public long ID { get; set; }
        public string From_Acc { get; set; }
        public string To_Acc { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string DateTime { get; set; }
        public Nullable<bool> IsRead_Sent { get; set; }
        public Nullable<bool> IsRead_Received { get; set; }
    }
}
