//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyTransfer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Notifications
    {
        public long ID { get; set; }
        public string UserName { get; set; }
        public string Admin_reply { get; set; }
        public Nullable<bool> IsRead { get; set; }
    }
}
